#ifndef BLAS_GLSL
#define BLAS_GLSL

// ---------------------------------------------------------------------------
// Bottom-level acceleration structure for sub-block geometry.
//
// The voxel grid is the top level: a DDA finds which block a ray enters. This
// file resolves what the ray hits *inside* that block, against the real box list
// Minecraft's own model declares for that blockstate.
//
// It replaces the old intersectVoxelShape() if-chain, which hardcoded 66 shapes
// and could not express connection state -- every fence traced as a full 4-way
// cross, and its two horizontal planks were modelled as one solid slat, so the
// gap between them never let light through. The table here is generated by
// scripts/gen_block_shapes.py straight from the game's blockstate/model JSON.
//
// Boxes are stored in the voxel's local 0..1 frame, quantised to 1/64 of a block
// (Minecraft authors models on a 1/16 grid, so 1/64 is exact for every vanilla
// shape and leaves headroom for element rotations that need conservative bounds).
// ---------------------------------------------------------------------------

#include "/lib/pt/voxelFormat.glsl"

// Filled once at pack load by the setup compute pass (program/setup/s0_shape_table.glsl).
layout(std430, binding = 0) buffer ShapeTableBuffer {
    // shapeId -> (boxOffset << 8) | boxCount. Index 0 is the full cube (no boxes).
    uint shapeLookup[1024];
    // Two uints per box; see unpackShapeBox below.
    uint shapeBoxes[];
} shapeTable;

// Matches pack_box() in scripts/gen_block_shapes.py:
//   lo = xmin | ymin<<8 | zmin<<16 | xmax<<24
//   hi = ymax | zmax<<8
void unpackShapeBox(uint idx, out vec3 bmin, out vec3 bmax) {
    uint lo = shapeTable.shapeBoxes[idx * 2u];
    uint hi = shapeTable.shapeBoxes[idx * 2u + 1u];
    const float K = 1.0 / 64.0;
    bmin = vec3(float( lo        & 255u),
                float((lo >>  8) & 255u),
                float((lo >> 16) & 255u)) * K;
    bmax = vec3(float((lo >> 24) & 255u),
                float( hi        & 255u),
                float((hi >>  8) & 255u)) * K;
}

uint shapeBoxOffset(uint shapeId) { return shapeTable.shapeLookup[shapeId] >> 8u; }
uint shapeBoxCount(uint shapeId)  { return shapeTable.shapeLookup[shapeId] & 255u; }

// Slab test against one box, keeping the nearest hit so far.
// skipInside drops boxes the ray origin already sits inside, which is how a
// surface avoids shadowing itself when a ray starts on its own block.
bool blasBoxHit(vec3 ro, vec3 ird, vec3 bmin, vec3 bmax, bool skipInside,
                inout float tBest, inout vec3 nBest) {
    vec3 t0  = (bmin - ro) * ird;
    vec3 t1  = (bmax - ro) * ird;
    vec3 tn3 = min(t0, t1);
    vec3 tf3 = max(t0, t1);
    float tn = max(tn3.x, max(tn3.y, tn3.z));
    float tf = min(tf3.x, min(tf3.y, tf3.z));
    if (tn > tf || tf < 0.0) return false;
    if (skipInside && tn <= 0.0) return false;
    float t = max(tn, 0.0);
    if (t >= tBest) return false;
    tBest = t;
    // Face normal is the slab whose entry distance won; sign opposes the ray.
    if (tn > 0.0) nBest = -sign(ird) * vec3(equal(vec3(tn), tn3));
    return true;
}

// Intersect a ray against a shape's box list. ro/rd are in the voxel's local
// 0..1 frame. Returns the nearest hit; tHit/nHit are only meaningful when true.
bool intersectShape(uint shapeId, vec3 ro, vec3 rd, bool skipInside,
                    out float tHit, out vec3 nHit) {
    tHit = 1e30;
    nHit = -rd; // fallback for a ray that starts inside the geometry
    if (shapeId == 0u) return false; // full cube: the voxel itself is the hit

    uint entry = shapeTable.shapeLookup[shapeId];
    uint count = entry & 255u;
    if (count == 0u) return false;
    uint base = entry >> 8u;

    vec3 ird = 1.0 / (rd + vec3(1e-8));
    bool hit = false;
    for (uint i = 0u; i < count; ++i) {
        vec3 bmin, bmax;
        unpackShapeBox(base + i, bmin, bmax);
        hit = blasBoxHit(ro, ird, bmin, bmax, skipInside, tHit, nHit) || hit;
    }
    return hit;
}

// Cheap any-hit variant for shadow/occlusion rays: no nearest-hit bookkeeping,
// stops at the first box the ray crosses within maxT.
bool occludeShape(uint shapeId, vec3 ro, vec3 rd, bool skipInside, float maxT) {
    if (shapeId == 0u) return true;
    uint entry = shapeTable.shapeLookup[shapeId];
    uint count = entry & 255u;
    if (count == 0u) return false;
    uint base = entry >> 8u;

    vec3 ird = 1.0 / (rd + vec3(1e-8));
    for (uint i = 0u; i < count; ++i) {
        vec3 bmin, bmax;
        unpackShapeBox(base + i, bmin, bmax);
        vec3 t0 = (bmin - ro) * ird;
        vec3 t1 = (bmax - ro) * ird;
        vec3 tn3 = min(t0, t1), tf3 = max(t0, t1);
        float tn = max(tn3.x, max(tn3.y, tn3.z));
        float tf = min(tf3.x, min(tf3.y, tf3.z));
        if (tn > tf || tf < 0.0) continue;
        if (skipInside && tn <= 0.0) continue;
        if (max(tn, 0.0) < maxT) return true;
    }
    return false;
}

#endif
